In [ ]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
raw_train = pd.read_csv('Train.csv')
raw_test = pd.read_csv('Test.csv')
df = raw_train.copy()
df_test = raw_test.copy()

In [ ]:
df.head(20)

,Uniq Id,Package Name,Package Type,Destination,Itinerary,Places Covered,Travel Date,Hotel Details,Start City,Airline,Flight Stops,Meals,Sightseeing Places Covered,Cancellation Rules,Per Person Price
0,e788ab76d9d8cf1e6ed2f139645ca5d1,Best of Shimla and Manali Holiday from Delhi,Standard,New Delhi|Shimla|Manali|Chandigarh,1N New Delhi . 2N Shimla . 2N Manali . 1N Chan...,New Delhi|Shimla|Manali|Chandigarh,30-07-2021,Not Available,Mumbai,Not Available,2,3,Not Available,Not Available,11509.0
1,178f892630ce3e335a5a41d5d83937fd,Kashmir Valley vacation,Premium,Srinagar|Pahalgam|Srinagar,1N Srinagar . 2N Pahalgam . 1N Srinagar,Srinagar|Pahalgam|Srinagar,08-12-2021,The Orchard Retreat & Spa:4.6|WelcomHotel Pine...,New Delhi,IndiGo,0,5,Dal Lake | Avantipura Ruins | Mughal Gardens ...,Cancellation any time after making the 1st pay...,22485.5
2,f060f2954840503cc2fdaf495357b7df,Might of Mewar- Udaipur and Chittorgarh,Luxury,Udaipur|Chittorgarh,2N Udaipur . 1N Chittorgarh,Udaipur|Chittorgarh,26-04-2021,The Ananta:4.4|juSTa Lake Nahargarh Palace:4,New Delhi,IndiGo,0,4,Lake Pichola | Jag Mandir Palace | Saheliyon ...,Cancellation any time after making the 1st pay...,12421.5
3,32a19a6c171e67448f2346da46c619dc,Colorful Kerala ( Romantic Getaway ),Premium,Munnar|Kumarakom|Allepey|Kovalam and Poovar,2N Munnar . 1N Kumarakom . 1N Allepey . 2N Kov...,Munnar|Kumarakom|Allepey|Kovalam and Poovar,27-08-2021,Elixir Hills Suites Resort & Spa-MMT Holidays ...,New Delhi,IndiGo,0,5,Mattupetty Dam | Echo Point | Tata Tea Museum...,Cancellation any time after making the 1st pay...,35967.0
4,107b068aa0ca03bc6248966f594d105f,A Week In Bangkok & Pattaya,Premium,Pattaya|Bangkok,4N Pattaya . 3N Bangkok,Pattaya|Bangkok,12-12-2021,Dusit Thani Pattaya - MMT Special:4.5|Amari Wa...,New Delhi,Spicejet|Go Air,0,5,"Coral Island Tour with Indian Lunch, Join Spe...",Cancellation any time after making the 1st pay...,25584.0
5,3bb074528941b3a6823371f77b07fb0f,Cochin Trip with Visit to Guruvayoor Temple,Deluxe,Cochin,2N Cochin,Cochin,30-09-2021,Not Available,Mumbai,IndiGo,1,3,Dutch Palace | Jewish Synagogue | St. Francis...,Not Available,8512.0
6,644c71b1a9ccfe6eacc6303be12c1352,Jaipur Holiday,Standard,Jaipur,3N Jaipur,Jaipur,24-01-2021,Ratnawali A Vegetarian Heritage Hotel:4.1,New Delhi,IndiGo,2,3,Hawa Mahal | City Palace | Jantar Mantar | Am...,Cancellation any time after making the 1st pay...,6848.0
7,07943295cfdce5cb20861e8369948b1d,Kasol & Manali holiday from Delhi,Deluxe,Kasol|Manali,2N Kasol . 3N Manali,Kasol|Manali,10-12-2021,The Himalayan Village:Four|The Holiday Resorts...,Mumbai,Not Available,1,3,Pandoh Dam | Hadimba Temple | Tibetan Monaste...,Cancellation any time after making the 1st pay...,14454.5
8,126e12c63233bf11ef2e001a062f2a53,Charismatic Kashmir with Gulmarg,Deluxe,Srinagar|Gulmarg|Pahalgam|Srinagar,1N Srinagar . 1N Gulmarg . 2N Pahalgam . 2N Sr...,Srinagar|Gulmarg|Pahalgam|Srinagar,03-10-2021,California Group of Houseboats:3.6|The Rosewoo...,New Delhi,IndiGo,1,3,Dal Lake | Gondola Point | Avantipura Ruins |...,Cancellation any time after making the 1st pay...,21556.5
9,72aeb7bac6d5600fe443fca06e3db631,Luxury Getaway to Udaipur - Stay at the Chunda...,Premium,Udaipur,2N Udaipur,Udaipur,15-08-2021,Chunda Palace:4.6,Mumbai,IndiGo,0,5,Lake Pichola | Jag Mandir Palace | Sajjangarh...,This cancellation policy is applicable for boo...,13042.0
10,e44087e386d00c5267679f8fd307b7f3,Essence of Kerala,Budget,Kovalam and Poovar|Kanyakumari,2N Kovalam and Poovar . 1N Kanyakumari,Kovalam and Poovar|Kanyakumari,02-06-2021,UDAY SAMUDRA LEISURE BEACH HOTEL & SPA-MMT Hol...,New Delhi,Spicejet,2,2,Hawa Beach | Light House Beach | Bhagavathy A...,Cancellation any time after making the 1st pay...,10648.5
11,0dbe8654ab9d0e6e7521307cf4e87df5,A Blissful holiday in Kerala,Premium,Cochin|Munnar|Allepey|Kovalam and Poovar,1N Cochin . 2N Munnar . 1N Allepey . 2N Kovala...,Cochin|Munnar|Allepey|Kovalam and Poovar,14-10-2021,Casino Hotel - Cgh Earth-MMT Holidays Special:...,New Delhi,IndiGo|Spicejet,0,5,Fort Cochin | Dutch Palace | Jewish Synagogue...,Cancellation any time after making the 1st pay...,25902.0
12,455c47ceb54f32117184ddac1f1d3381,A day visit to Guwahati,Premium,Guwahati,1N Guwahati,Guwahati,15-09-2021,Kiranshree Grand:4.5,New Delhi,Spicejet,0,5,Kamakhya Temple,Cancellation any time after making the 1st pay...,12009.5
13,3429b7d0a59153d4208e1da2c6375fd6,Holiday in Udaipur & Mount Abu by Volvo from A...,Standard,Udaipur|Mount Abu,2N Udaipur . 1N Mount Abu,Udaipur|Mount Abu,21-05-2021,Not Available,New Delhi,Not Available,2,3,Lake Pichola | Jag Mandir Palace | Return Vol...,Cancellation any time after making the 1st pay...,6911.0
14,6cd8532dfd379fa163d78c2d6e2fb4b2,Himachal Marvels from Delhi(with Flights),Deluxe,Chandigarh|Shimla|Manali|Chandigarh,1N Chandigarh . 2N Shimla . 3N Manali . 1N Cha...,Chandigarh|Shimla|Manali|Chandigarh,19-02-2021,Hotel 6 Chandigarh Zirakpur(Medallion):4|Summi...,Mumbai,Go Air|IndiGo,1,3,Pinjore Gardens | Shimla Church | Scandal poi...,Cancellation any time after making the 1st pay...,17323.0
15,fac47ae77eab1c689848f4b25d45cef8,"Drive to Nainital, Kausani and Corbett",Standard,Nainital|Kausani|Corbett,2N Nainital . 1N Kausani . 2N Corbett,Nainital|Kausani|Corbett,29-06-2021,Hotel Maya Regency Bhimtal:3.8|Heritage Resort...,New Delhi,IndiGo,2,3,Nainital Zoo | Naina devi Temple | Lands End ...,Cancellation any time after making the 1st pay...,13890.0
16,59bb52b95f9f1cbcb5350b50c0c8f9b2,Romantic Getaway - Spectacular Landscapes of K...,Deluxe,Kodaikanal,3N Kodaikanal,Kodaikanal,18-12-2021,Kodai Resort Hotel:4.1,New Delhi,Air India,1,3,South India - Convenience Value pack - Sedan ...,This cancellation policy is applicable for boo...,14558.5
17,7c21b76443e81009f0851635819465f5,Beautiful Kashmir Holiday,Deluxe,Srinagar|Gulmarg|Srinagar,1N Srinagar . 1N Gulmarg . 2N Srinagar,Srinagar|Gulmarg|Srinagar,09-04-2021,California Group of Houseboats:3.6|The Rosewoo...,Mumbai,Spicejet,1,3,Dal Lake | Gondola Point | Mughal Gardens | C...,Cancellation any time after making the 1st pay...,12591.0
18,d26163e7ff27bf1e8637728c785df0db,A Relaxing Rendezvous in Himachal from Delhi,Luxury,Shimla|Manali|Dharamshala,2N Shimla . 3N Manali . 2N Dharamshala,Shimla|Manali|Dharamshala,27-11-2021,Not Available,Mumbai,Not Available,0,4,Kufri | Mall road | Viceregal Lodge | Pandoh ...,Cancellation any time after making the 1st pay...,20739.0
19,d6d306cb2a359396aefb53ec5fbff2d7,Queen of Hill Stations,Standard,Ooty|Kodaikanal,3N Ooty . 3N Kodaikanal,Ooty|Kodaikanal,22-11-2021,Hotel Meadows Residency:4.4|Hotel Jem Valley:3.8,Mumbai,Spicejet,2,3,Ooty Lake | Doddabetta Peak | Ooty Botanical ...,Cancellation any time after making the 1st pay...,14445.0

In [ ]:
df = df.set_index('Uniq Id')
df_test = df_test.set_index('Uniq Id')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21000 entries, e788ab76d9d8cf1e6ed2f139645ca5d1 to 5ed596587aba74b3f52a59384c04b5a4
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Package Name                21000 non-null  object
 1   Package Type                21000 non-null  object
 2   Destination                 21000 non-null  object
 3   Itinerary                   21000 non-null  object
 4   Places Covered              21000 non-null  object
 5   Travel Date                 21000 non-null  object
 6   Hotel Details               21000 non-null  object
 7   Start City                  21000 non-null  object
 8   Airline                     21000 non-null  object
 9   Flight Stops                21000 non-null  int64
 10  Meals                       21000 non-null  int64
 11  Sightseeing Places Covered  21000 non-null  object
 12  Cancellation Rules          21000 non-null  object
 13  Per Person Price            21000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 2.4+ MB

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9000 entries, 12c47aefbcca65d6156ba0bc7946704b to 63f248718bd829ec8a3d234f85637734
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Package Name                9000 non-null   object
 1   Package Type                9000 non-null   object
 2   Destination                 9000 non-null   object
 3   Itinerary                   9000 non-null   object
 4   Places Covered              9000 non-null   object
 5   Travel Date                 9000 non-null   object
 6   Hotel Details               9000 non-null   object
 7   Start City                  9000 non-null   object
 8   Airline                     9000 non-null   object
 9   Flight Stops                9000 non-null   int64
 10  Meals                       9000 non-null   int64
 11  Sightseeing Places Covered  9000 non-null   object
 12  Cancellation Rules          9000 non-null   object
dtypes: int64(2), object(11)
memory usage: 984.4+ KB

No Null Values in both Train and Test set, Given is a Regression problem with Target variable as Per Person Price

- add total no of nights and total no of places in the package form Itinerary column - total_N, total_P
- remove Itinerary        - 
- remove Places Covered
- remove Destination
- remove Sightseeing Places Covered
- do something with Travel Date column
- Airline column contains Not Available values and also repeating values
- do something with Cancellation Rules column

In [ ]:
print(df.shape, df_test.shape)

(21000, 14) (9000, 13)

In [ ]:
#removing duplicate rows
df.drop_duplicates(inplace = True)

In [ ]:
print(df.shape, df_test.shape)

(20997, 14) (9000, 13)

### Travel Date

In [ ]:
df['Travel Date'] = pd.to_datetime(df['Travel Date'], dayfirst=True)
df_test['Travel Date'] = pd.to_datetime(df_test['Travel Date'], dayfirst=True)
# dir(df['Travel Date'].dt)

In [ ]:
print(df['Travel Date'].min(), df['Travel Date'].max())
print(df_test['Travel Date'].min(), df_test['Travel Date'].max())

2021-01-01 00:00:00 2022-05-18 00:00:00
2021-01-06 00:00:00 2022-05-16 00:00:00

In [ ]:
date_features = [
                 'month',
                 'weekday',
                 'is_month_end',
                 'is_month_start',
                 'is_year_end',
                 'is_year_start',
                ]

dt_attr = getattr(df['Travel Date'], 'dt')
dt_attr2 = getattr(df_test['Travel Date'], 'dt')
for feat in date_features:
    df[feat] = getattr(dt_attr, feat)
    df_test[feat] = getattr(dt_attr2, feat)

In [ ]:
print(df.columns)
df.head()

Index(['Package Name', 'Package Type', 'Destination', 'Itinerary',
       'Places Covered', 'Travel Date', 'Hotel Details', 'Start City',
       'Airline', 'Flight Stops', 'Meals', 'Sightseeing Places Covered',
       'Cancellation Rules', 'Per Person Price', 'month', 'weekday',
       'is_month_end', 'is_month_start', 'is_year_end', 'is_year_start'],
      dtype='object')

,Package Name,Package Type,Destination,Itinerary,Places Covered,Travel Date,Hotel Details,Start City,Airline,Flight Stops,Meals,Sightseeing Places Covered,Cancellation Rules,Per Person Price,month,weekday,is_month_end,is_month_start,is_year_end,is_year_start
Uniq Id,,,,,,,,,,,,,,,,,,,,
e788ab76d9d8cf1e6ed2f139645ca5d1,Best of Shimla and Manali Holiday from Delhi,Standard,New Delhi|Shimla|Manali|Chandigarh,1N New Delhi . 2N Shimla . 2N Manali . 1N Chan...,New Delhi|Shimla|Manali|Chandigarh,2021-07-30,Not Available,Mumbai,Not Available,2,3,Not Available,Not Available,11509.0,7,4,False,False,False,False
178f892630ce3e335a5a41d5d83937fd,Kashmir Valley vacation,Premium,Srinagar|Pahalgam|Srinagar,1N Srinagar . 2N Pahalgam . 1N Srinagar,Srinagar|Pahalgam|Srinagar,2021-12-08,The Orchard Retreat & Spa:4.6|WelcomHotel Pine...,New Delhi,IndiGo,0,5,Dal Lake | Avantipura Ruins | Mughal Gardens ...,Cancellation any time after making the 1st pay...,22485.5,12,2,False,False,False,False
f060f2954840503cc2fdaf495357b7df,Might of Mewar- Udaipur and Chittorgarh,Luxury,Udaipur|Chittorgarh,2N Udaipur . 1N Chittorgarh,Udaipur|Chittorgarh,2021-04-26,The Ananta:4.4|juSTa Lake Nahargarh Palace:4,New Delhi,IndiGo,0,4,Lake Pichola | Jag Mandir Palace | Saheliyon ...,Cancellation any time after making the 1st pay...,12421.5,4,0,False,False,False,False
32a19a6c171e67448f2346da46c619dc,Colorful Kerala ( Romantic Getaway ),Premium,Munnar|Kumarakom|Allepey|Kovalam and Poovar,2N Munnar . 1N Kumarakom . 1N Allepey . 2N Kov...,Munnar|Kumarakom|Allepey|Kovalam and Poovar,2021-08-27,Elixir Hills Suites Resort & Spa-MMT Holidays ...,New Delhi,IndiGo,0,5,Mattupetty Dam | Echo Point | Tata Tea Museum...,Cancellation any time after making the 1st pay...,35967.0,8,4,False,False,False,False
107b068aa0ca03bc6248966f594d105f,A Week In Bangkok & Pattaya,Premium,Pattaya|Bangkok,4N Pattaya . 3N Bangkok,Pattaya|Bangkok,2021-12-12,Dusit Thani Pattaya - MMT Special:4.5|Amari Wa...,New Delhi,Spicejet|Go Air,0,5,"Coral Island Tour with Indian Lunch, Join Spe...",Cancellation any time after making the 1st pay...,25584.0,12,6,False,False,False,False

### Itinerary

In [ ]:
df['Itinerary']

Uniq Id
e788ab76d9d8cf1e6ed2f139645ca5d1    1N New Delhi . 2N Shimla . 2N Manali . 1N Chan...
178f892630ce3e335a5a41d5d83937fd              1N Srinagar . 2N Pahalgam . 1N Srinagar
f060f2954840503cc2fdaf495357b7df                          2N Udaipur . 1N Chittorgarh
32a19a6c171e67448f2346da46c619dc    2N Munnar . 1N Kumarakom . 1N Allepey . 2N Kov...
107b068aa0ca03bc6248966f594d105f                              4N Pattaya . 3N Bangkok
                                                          ...
ae3ae6ca299180d470145a0e154cbf2b                 2N Shimla . 3N Manali . 1N New Delhi
6ccc538e3597a909f609fcb2eba9be5e    1N Srinagar . 1N Gulmarg . 2N Pahalgam . 3N Sr...
d3b412fa94ce5503204024c6db2f60b7                                           5N Colombo
51d843fb852ec7abde8299fe31111bd5              2N Darjeeling . 2N Pelling . 2N Gangtok
5ed596587aba74b3f52a59384c04b5a4                  3N Munnar . 2N Kovalam . 1N Allepey
Name: Itinerary, Length: 20997, dtype: object

In [ ]:
nights = []
places = []
for i in range(0,len(df['Itinerary'])):
    arr = df['Itinerary'][i].split('.')
    p_cnt = 0
    n_cnt = 0
    for j in range(0, len(arr)):
        p_cnt = p_cnt + 1
        arr[j] = arr[j].strip()
        n_cnt = n_cnt + int(arr[j][0])
    #print(arr)
    nights.append(n_cnt)
    places.append(p_cnt)

In [ ]:
df['total_N'] = nights
df['total_P'] = places

In [ ]:
nights = []
places = []
for i in range(0,len(df_test['Itinerary'])):
    arr = df_test['Itinerary'][i].split('.')
    p_cnt = 0
    n_cnt = 0
    for j in range(0, len(arr)):
        p_cnt = p_cnt + 1
        arr[j] = arr[j].strip()
        n_cnt = n_cnt + int(arr[j][0])
    #print(arr)
    nights.append(n_cnt)
    places.append(p_cnt)

In [ ]:
df_test['total_N'] = nights
df_test['total_P'] = places

In [ ]:
print(df.columns)
df.head()

Index(['Package Name', 'Package Type', 'Destination', 'Itinerary',
       'Places Covered', 'Travel Date', 'Hotel Details', 'Start City',
       'Airline', 'Flight Stops', 'Meals', 'Sightseeing Places Covered',
       'Cancellation Rules', 'Per Person Price', 'month', 'weekday',
       'is_month_end', 'is_month_start', 'is_year_end', 'is_year_start',
       'total_N', 'total_P'],
      dtype='object')

,Package Name,Package Type,Destination,Itinerary,Places Covered,Travel Date,Hotel Details,Start City,Airline,Flight Stops,...,Cancellation Rules,Per Person Price,month,weekday,is_month_end,is_month_start,is_year_end,is_year_start,total_N,total_P
Uniq Id,,,,,,,,,,,,,,,,,,,,,
e788ab76d9d8cf1e6ed2f139645ca5d1,Best of Shimla and Manali Holiday from Delhi,Standard,New Delhi|Shimla|Manali|Chandigarh,1N New Delhi . 2N Shimla . 2N Manali . 1N Chan...,New Delhi|Shimla|Manali|Chandigarh,2021-07-30,Not Available,Mumbai,Not Available,2,...,Not Available,11509.0,7,4,False,False,False,False,6,4
178f892630ce3e335a5a41d5d83937fd,Kashmir Valley vacation,Premium,Srinagar|Pahalgam|Srinagar,1N Srinagar . 2N Pahalgam . 1N Srinagar,Srinagar|Pahalgam|Srinagar,2021-12-08,The Orchard Retreat & Spa:4.6|WelcomHotel Pine...,New Delhi,IndiGo,0,...,Cancellation any time after making the 1st pay...,22485.5,12,2,False,False,False,False,4,3
f060f2954840503cc2fdaf495357b7df,Might of Mewar- Udaipur and Chittorgarh,Luxury,Udaipur|Chittorgarh,2N Udaipur . 1N Chittorgarh,Udaipur|Chittorgarh,2021-04-26,The Ananta:4.4|juSTa Lake Nahargarh Palace:4,New Delhi,IndiGo,0,...,Cancellation any time after making the 1st pay...,12421.5,4,0,False,False,False,False,3,2
32a19a6c171e67448f2346da46c619dc,Colorful Kerala ( Romantic Getaway ),Premium,Munnar|Kumarakom|Allepey|Kovalam and Poovar,2N Munnar . 1N Kumarakom . 1N Allepey . 2N Kov...,Munnar|Kumarakom|Allepey|Kovalam and Poovar,2021-08-27,Elixir Hills Suites Resort & Spa-MMT Holidays ...,New Delhi,IndiGo,0,...,Cancellation any time after making the 1st pay...,35967.0,8,4,False,False,False,False,6,4
107b068aa0ca03bc6248966f594d105f,A Week In Bangkok & Pattaya,Premium,Pattaya|Bangkok,4N Pattaya . 3N Bangkok,Pattaya|Bangkok,2021-12-12,Dusit Thani Pattaya - MMT Special:4.5|Amari Wa...,New Delhi,Spicejet|Go Air,0,...,Cancellation any time after making the 1st pay...,25584.0,12,6,False,False,False,False,7,2

### Airline

In [ ]:
df['Airline'].unique()

array(['Not Available', 'IndiGo', 'Spicejet|Go Air', 'Spicejet',
       'IndiGo|Spicejet', 'Go Air|IndiGo', 'Air India', 'Go Air',
       'Emirates', 'Spicejet|Air India', 'Vistara', 'Spicejet|IndiGo',
       'Thai Airways|AirAsia Indonesia|Srilankan Airlines',
       'Srilankan Airlines', 'Air India|Spicejet', 'Spicejet|AirAsia',
       'Spicejet|Vistara', 'Air India Express',
       'Malindo Air|AirAsia Indonesia|Malindo Air', 'Air India|IndiGo',
       'Malaysia Airlines', 'Vistara|Spicejet', 'AirAsia|Spicejet',
       'Vistara|Go Air',
       'IndiGo|Qantas Airways|Air New Zealand|Singapore Airlines',
       'Air India|Air Seychelles|Etihad Airways', 'Go Air|Air India',
       'Malindo Air|AirAsia X|Malindo Air', 'Thai Airways', 'Malindo Air',
       'IndiGo|Go Air', 'Vistara|IndiGo', 'Go Air|Spicejet',
       'AirAsia X|AirAsia Indonesia|AirAsia X',
       'Malindo Air|Scoot|Spicejet', 'Malindo Air|AirAsia X',
       'Air Mauritius|Emirates', 'Oman Air',
       'Thai Airways|Thai AirAsia|Vistara', 'Malindo Air|IndiGo',
       'AirAsia|IndiGo', 'IndiGo|Vistara', 'AirAsia|Go Air',
       'Srilankan Airlines|Jetstar Asia|Srilankan Airlines',
       'Srilankan Airlines|Malindo Air',
       'Air India|Thai Airways|Singapore Airlines|Air India',
       'Singapore Airlines', 'AirAsia X',
       'IndiGo|Air India Express|Spicejet', 'Saudia',
       'Thai Airways|Thai AirAsia|Spicejet', 'Go Air|Vistara',
       'Malindo Air|Thai AirAsia|Malindo Air', 'Air India|Go Air',
       'AirAsia|Vistara', 'Spicejet|Thai AirAsia X', 'IndiGo|Air India',
       'IndiGo|AirAsia', 'Go Air|AirAsia',
       'Malindo Air|AirAsia|Malindo Air', 'Vistara|Air India',
       'Emirates|Go Air', 'AirAsia X|AirAsia|Malindo Air',
       'Malaysia Airlines|Thai Airways|Malaysia Airlines',
       'Spicejet|Thai Vietjet Air|Go Air',
       'IndiGo|Malaysia Airlines|Go Air', 'EgyptAir',
       'Malindo Air|Thai AirAsia|Spicejet',
       'Air India|Thai Airways|Garuda Indonesia|Malindo Air',
       'Air Mauritius', 'Air India Express|IndiGo',
       'IndiGo|Silkair|Go Air', 'IndiGo|Malindo Air|IndiGo',
       'Go Air|Thai Vietjet Air|Bangkok Airways',
       'Vistara|Scoot|Malindo Air',
       'Srilankan Airlines|Malaysia Airlines|Go Air',
       'IndiGo|Air India Express', 'Srilankan Airlines|IndiGo',
       'Air Mauritius|Kenya Airways', 'Aeroflot',
       'Spicejet|Thai Vietjet Air|Bangkok Airways', 'Bangkok Airways',
       'Go Air|Thai Vietjet Air|Go Air',
       'Vistara|Philippine Airlines|Jetstar Airways|Emirates',
       'Air India|AirAsia Indonesia|AirAsia X', 'Qantas Airways',
       'IndiGo|Garuda Indonesia|Malindo Air',
       'Malindo Air|AirAsia Indonesia|Srilankan Airlines',
       'AirAsia X|AirAsia|Thai AirAsia|Vistara', 'Etihad Airways',
       'Spicejet|Scoot|Spicejet', 'Malindo Air|Scoot|Air India',
       'Vistara|AirAsia Indonesia|Malindo Air',
       'Malaysia Airlines|Bangkok Airways|Thai Airways',
       'Malaysia Airlines|Qantas Airways',
       'Malindo Air|AirAsia Indonesia|Scoot|Malindo Air',
       'Air India|AirAsia', 'Srilankan Airlines|AirAsia|Malindo Air',
       'Vistara|Garuda Indonesia|Malindo Air',
       'Singapore Airlines|Silkair|Singapore Airlines',
       'Go Air|Bangkok Airways|Go Air',
       'Malindo Air|Scoot|Malaysia Airlines',
       'Malindo Air|Malaysia Airlines|Go Air',
       'AirAsia X|AirAsia|Scoot|Malindo Air', 'AirAsia|Air India',
       'Malindo Air|Scoot|Malindo Air', 'Air India|Vistara',
       'Vistara|Thai AirAsia X',
       'Singapore Airlines|Malaysia Airlines|Singapore Airlines',
       'Air India|Swiss', 'Malaysia Airlines|Malindo Air|IndiGo',
       'IndiGo|Emirates|Qantas Airways|Air New Zealand|Emirates',
       'Thai Airways|Scoot|Srilankan Airlines',
       'Spicejet|Air India Express|IndiGo',
       'Go Air|Thai Vietjet Air|Spicejet', 'Gulf Air|Lufthansa',
       'Vistara|Singapore Airlines|Go Air', 'AirAsia',
       'Malindo Air|Garuda Indonesia|Malindo Air',
       'Air Seychelles|Air India', 'Spicejet|IndiGo|Air India',
       'Air India Express|Spicejet',
       'Air India|Air Baltic|Uzbekistan Airways',
       'Thai Airways|AirAsia Indonesia|Malindo Air', 'Swiss|Lufthansa',
       'Air India|Lufthansa', 'Vistara|Scoot|Spicejet',
       'Malindo Air|Scoot|Vistara', 'Spicejet|IndiGo|Go Air',
       'Air India|Kuwait Airways', 'IndiGo|Jetstar Asia|Go Air',
       'Air India|Malaysia Airlines|Air New Zealand|China Southern',
       'Srilankan Airlines|AirAsia Indonesia|AirAsia X',
       'Malindo Air|AirAsia Indonesia|AirAsia X',
       'Air India|Finnair|Qatar Airways', 'Bangkok Airways|Spicejet',
       'Singapore Airlines|Air New Zealand|Singapore Airlines',
       'AirAsia X|AirAsia Indonesia|AirAsia|Malindo Air',
       'IndiGo|Philippine Airlines|Air New Zealand|Singapore Airlines',
       'Spicejet|IndiGo|Vistara', 'Malaysia Airlines|EgyptAir',
       'Lufthansa', 'Vistara|AirAsia',
       'Singapore Airlines|Bangkok Airways|Srilankan Airlines',
       'Singapore Airlines|Airconnect|Singapore Airlines',
       'IndiGo|Emirates|Etihad Airways', 'Malindo Air|Spicejet',
       'Air India|Air Mauritius|Air India',
       'Thai Airways|Malindo Air|IndiGo', 'Spicejet|Air India|IndiGo',
       'Malindo Air|Thai AirAsia|Vistara',
       'IndiGo|Singapore Airlines|Go Air',
       'Malindo Air|Scoot|Srilankan Airlines', 'IndiGo|Malindo Air',
       'Singapore Airlines|Bangkok Airways|Thai Airways',
       'Air India|China Eastern|Air New Zealand|Singapore Airlines',
       'Thai Airways|AirAsia|Malindo Air',
       'AirAsia X|AirAsia Indonesia|Malindo Air',
       'Malaysia Airlines|AirAsia|Malindo Air', 'Vistara|Scoot|Air India',
       'Air India|Norwegian|British Airways|Virgin Atlantic',
       'Turkish Airlines|Brussels Airlines|Oman Air',
       'Malindo Air|AirAsia Indonesia|Air India',
       'Air India|Air New Zealand|Emirates',
       'Cathay Pacific|Qantas Airways|Cathay Pacific',
       'AirAsia X|Malindo Air', 'Air Seychelles',
       'Srilankan Airlines|Qantas Airways', 'Singapore Airlines|IndiGo',
       'Air India|Thai Airways|Malindo Air|IndiGo',
       'Thai Airways|Garuda Indonesia|Malindo Air',
       'Air Seychelles|Air Austral|Air India',
       'Singapore Airlines|Malindo Air',
       'Singapore Airlines|Silkair|Malindo Air|IndiGo',
       'IndiGo|Spicejet|IndiGo', 'Thai Airways|Scoot|AirAsia X',
       'Malaysia Airlines|Jetstar Airways|Emirates',
       'Vistara|AirAsia Indonesia|AirAsia X',
       'Thai Airways|AirAsia Indonesia|AirAsia X',
       'IndiGo|Air India|IndiGo', 'British Airways',
       'IndiGo|Srilankan Airlines', 'EgyptAir|Air Baltic|Oman Air',
       'Air New Zealand', 'Turkish Airlines',
       'Srilankan Airlines|Scoot|Spicejet',
       'Air India|Thai Airways|AirAsia Indonesia|Srilankan Airlines',
       'Air India|AirAsia Indonesia|Malindo Air',
       'Malaysia Airlines|Thai Airways',
       'Cathay Pacific|Bangkok Airways|Thai Airways',
       'Emirates|South African Airways|Air India',
       'Air India|Air Seychelles|Ethiopian Airlines',
       'Emirates|Air Mauritius', 'IndiGo|Spicejet|Vistara',
       'Qantas Airways|Singapore Airlines',
       'Air India|Qantas Airways|Singapore Airlines',
       'Turkish Airlines|Finnair|Turkish Airlines',
       'Vistara|Malaysia Airlines|Air New Zealand|Emirates',
       'Go Air|Bangkok Airways',
       'Malaysia Airlines|Cathay Pacific|Malaysia Airlines',
       'Turkish Airlines|Sichuan Airlines|Qatar Airways',
       'Malindo Air|AirAsia Indonesia|Scoot|AirAsia X', 'Kuwait Airways',
       'Spicejet|IndiGo|Spicejet', 'Emirates|IndiGo',
       'Turkish Airlines|Norwegian|Etihad Airways',
       'Cathay Pacific|Qantas Airways|Air New Zealand|Cathay Pacific',
       'Cathay Pacific|Singapore Airlines|Malaysia Airlines',
       'Malindo Air|Srilankan Airlines',
       'Malaysia Airlines|AirAsia Indonesia|AirAsia X',
       'Thai Airways|Malindo Air'], dtype=object)

In [ ]:
airlines = []
for i in range(0,len(df['Airline'])):
    arr = df['Airline'][i].split('|')
    air_set = {""}
    for j in range(0, len(arr)):
        arr[j] = arr[j].strip()
        air_set.add(arr[j])
    air_set.remove('')
    arr = []
    for x in air_set:
        arr.append(x)
    arr.sort()
    ans = ""
    for i in range(len(arr)):
        if i != 0:
            ans = ans + '|' + arr[i]
        else:
            ans = arr[i]
    airlines.append(ans)
df['Airline'] = airlines

In [ ]:
airlines = []
for i in range(0,len(df_test['Airline'])):
    arr = df_test['Airline'][i].split('|')
    air_set = {""}
    for j in range(0, len(arr)):
        arr[j] = arr[j].strip()
        air_set.add(arr[j])
    air_set.remove('')
    arr = []
    for x in air_set:
        arr.append(x)
    arr.sort()
    ans = ""
    for i in range(len(arr)):
        if i != 0:
            ans = ans + '|' + arr[i]
        else:
            ans = arr[i]
    airlines.append(ans)
df_test['Airline'] = airlines

In [ ]:
print(df['Airline'].nunique(), df_test['Airline'].nunique())

176 117

In [ ]:
# flights = {""}
# for i in range(0,len(df['Airline'])):
#     arr = df['Airline'][i].split('|')
#     for j in range(0, len(arr)):
#         arr[j] = str(arr[j]).strip()
#         flights.add(arr[j])
# flights.remove('')
# flights.remove('Not Available')        
# print(flights)

In [ ]:
df['Airline'].replace('Not Available', np.nan, inplace=True)
df_test['Airline'].replace('Not Available', np.nan, inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20997 entries, e788ab76d9d8cf1e6ed2f139645ca5d1 to 5ed596587aba74b3f52a59384c04b5a4
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Package Name                20997 non-null  object
 1   Package Type                20997 non-null  object
 2   Destination                 20997 non-null  object
 3   Itinerary                   20997 non-null  object
 4   Places Covered              20997 non-null  object
 5   Travel Date                 20997 non-null  datetime64[ns]
 6   Hotel Details               20997 non-null  object
 7   Start City                  20997 non-null  object
 8   Airline                     16090 non-null  object
 9   Flight Stops                20997 non-null  int64
 10  Meals                       20997 non-null  int64
 11  Sightseeing Places Covered  20997 non-null  object
 12  Cancellation Rules          20997 non-null  object
 13  Per Person Price            20997 non-null  float64
 14  month                       20997 non-null  int64
 15  weekday                     20997 non-null  int64
 16  is_month_end                20997 non-null  bool
 17  is_month_start              20997 non-null  bool
 18  is_year_end                 20997 non-null  bool
 19  is_year_start               20997 non-null  bool
 20  total_N                     20997 non-null  int64
 21  total_P                     20997 non-null  int64
dtypes: bool(4), datetime64[ns](1), float64(1), int64(6), object(10)
memory usage: 3.7+ MB

In [ ]:
df['Per Person Price'] = np.log1p(df['Per Person Price'])